#!/usr/bin/env python3
"""
LetterCracker — Dictionary Splitter
====================================
Run this script to regenerate all 9 word shard files from a raw word list.

Usage:
    python split-dictionary.py words_alpha.txt

The script reads your raw word list (one word per line), cleans it,
and generates 9 .js files in the word-shards/ folder.

You can use any plain text word list — one word per line.
Recommended source: https://github.com/dwyl/english-words/raw/master/words_alpha.txt
"""

import sys, os, json
from collections import Counter

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else 'words_alpha.txt'
    if not os.path.exists(src):
        print(f'ERROR: File not found: {src}')
        print('Usage: python split-dictionary.py words_alpha.txt')
        sys.exit(1)

    print(f'Reading {src}...')
    with open(src, 'r', encoding='utf-8', errors='ignore') as f:
        raw = f.read()

    words = sorted(set(
        w.strip().lower()
        for w in raw.replace('\r','').split('\n')
        if w.strip().isalpha() and len(w.strip()) >= 2
    ))
    print(f'Loaded {len(words):,} clean words')

    SHARDS = [
        ('wd-2-4',   list(range(2, 5)),  '2-4 letter words'),
        ('wd-5-6',   list(range(5, 7)),  '5-6 letter words'),
        ('wd-7',     [7],                '7 letter words'),
        ('wd-8',     [8],                '8 letter words'),
        ('wd-9',     [9],                '9 letter words'),
        ('wd-10',    [10],               '10 letter words'),
        ('wd-11-12', list(range(11,13)), '11-12 letter words'),
        ('wd-13-15', list(range(13,16)), '13-15 letter words'),
        ('wd-16up',  list(range(16,100)),'16+ letter words'),
    ]

    out_dir = 'word-shards'
    os.makedirs(out_dir, exist_ok=True)

    total = 0
    for name, lengths, label in SHARDS:
        shard_words = [w for w in words if len(w) in lengths]
        js = (
            f'/* LetterCracker Word Shard — {label} */\n'
            f'/* {len(shard_words):,} words | Auto-generated by split-dictionary.py */\n'
            f'if(!window.LC_SHARDS)window.LC_SHARDS={{}};\n'
            f'window.LC_SHARDS["{name}"]={json.dumps(shard_words, separators=(",",":"))};'
        )
        path = os.path.join(out_dir, f'{name}.js')
        with open(path, 'w', encoding='utf-8') as f:
            f.write(js)
        kb = os.path.getsize(path) / 1024
        print(f'  ✓ {name}.js — {len(shard_words):,} words — {kb:.0f} KB')
        total += len(shard_words)

    print(f'\nDone! {total:,} words across {len(SHARDS)} shards in {out_dir}/')
    print('Upload the word-shards/ folder to your GitHub repo.')

if __name__ == '__main__':
    main()
