// LetterCracker — Words Database
// Expanded word list: 5,194 words (2–8 letters)
// Covers common English, Scrabble TWL/SOWPODS, scientific & technical terms

const WORD_DB = {
  // Scrabble point values
  letterPoints: {
    a:1,b:3,c:3,d:2,e:1,f:4,g:2,h:4,i:1,j:8,k:5,l:1,m:3,
    n:1,o:1,p:3,q:10,r:1,s:1,t:1,u:1,v:4,w:4,x:8,y:4,z:10
  },

  // Comprehensive word list (5,194 words, 2–8 letters)
  words: [
    "aa","aalii","ab","aba","abaci","aback","abacs","abaft","abandon","abase",
    "abash","abask","abate","abaya","abbes","abbey","abbot","abcee","abeam","abear",
    "abele","aberr","abets","abhor","abide","abies","ability","abing","abins","abism",
    "abits","ablaze","able","ablet","abloom","ablow","abmho","abode","abohm","abolish",
    "aboon","abore","abort","abram","abray","abrim","abrin","abris","abroad","abs",
    "absence","absent","absey","absit","absolute","absorb","absorbed","abstain","abstract","absurd",
    "abuna","abune","abuse","abuts","abuzz","abyes","abysm","abyss","academic","acais",
    "acari","accent","accept","access","acclaim","accord","account","accoy","accurate","accuse",
    "ace","aced","acer","acerb","aces","aceta","acetal","acetic","acetyl","ached",
    "aches","achier","achieve","achieved","aching","achoo","acid","acidic","acids","ackee",
    "acme","acmes","acned","acnes","acock","acold","acorn","acquire","acquired","acquit",
    "acre","acred","acres","acrid","across","act","acted","actin","action","active",
    "actively","acton","actos","acts","actual","acute","ad","adage","adapt","adapted",
    "adapter","adbot","add","added","adder","addle","addled","address","adenine","adens",
    "adept","adequate","adhere","adjoin","adjust","adjusted","admire","admit","ado","adobe",
    "adopt","adore","adorn","ads","adult","advanced","advent","adverse","advice","adz",
    "ae","aeons","aerial","aerie","afar","affable","affected","affluent","afford","afield",
    "aflame","afloat","afoul","afraid","aft","after","ag","again","against","agate",
    "agave","agaze","age","aged","agency","agenda","agene","agent","ages","agger",
    "aggie","aggro","aghas","aghast","agile","agios","agism","agist","agleam","aglee",
    "aglet","agley","aglitter","aglow","agmas","ago","agoge","agone","agons","agony",
    "agora","agree","agreed","ags","ah","aha","ahead","aheap","ahing","ai",
    "aid","aide","aided","aids","ailing","ailment","aim","aimer","aims","ainee",
    "aioli","air","aired","airer","airey","airport","airs","airth","airts","airway",
    "aisle","ait","aitch","ajiva","ajuga","ajwan","akela","akene","akin","akins",
    "al","alack","alamo","alane","alang","alanine","alaninyl","alans","alarm","alarming",
    "alary","alate","alays","alb","albeit","albino","album","alcove","ale","alert",
    "algae","algal","algid","algin","algor","alias","alibi","alien","align","aligned",
    "alike","alkane","alkene","alkyl","alkyne","all","allay","alleged","allegro","alliance",
    "allied","allod","allowed","almost","aloe","aloft","alone","along","aloof","aloud",
    "alp","alpine","als","also","alt","altar","alter","altered","altho","although",
    "alto","alum","alums","always","am","ama","amaze","amber","ambient","ambit",
    "amble","ambush","ameba","ameer","amen","amend","amends","ami","amid","amide",
    "amidst","amine","amino","amish","amiss","amity","ammonia","amok","among","amount",
    "amour","amp","ample","amps","amu","amuse","amyl","amylase","amyloid","amyls",
    "an","ana","analysis","anchor","ancient","and","ands","anear","anele","anemia",
    "anew","angel","anger","angle","angled","angry","angst","aniline","aniliny","animal",
    "animated","anime","anise","ankle","anneal","annex","annoy","answer","ant","ante",
    "anti","antic","antics","antique","antler","ants","anvil","anxiety","anxious","any",
    "anyone","anyway","aorta","apart","ape","aper","apex","apian","apish","aplomb",
    "apode","apods","aport","appall","appealed","appeared","append","apple","applied","apply",
    "approve","apt","aptly","ar","arable","araby","arbor","arc","arced","arces",
    "arch","arched","archway","arcs","arctic","ardor","are","area","areae","areal",
    "areca","areic","arena","argal","arginine","argon","argot","argued","argument","argus",
    "aria","arid","ariel","arise","arista","ark","arm","armed","armet","armor",
    "army","aroma","arose","around","arouse","arpen","arrau","array","arrival","arrive",
    "arrived","arrow","arses","arson","art","article","artist","artistic","arts","as",
    "ascend","ascends","ascot","ascribe","asdic","ash","ashed","ashen","ashy","aside",
    "ask","asked","askew","asks","asleep","asp","aspect","aspen","aspirin","ass",
    "assail","assails","assault","assay","assent","assents","assert","asset","assign","assigned",
    "assigns","assist","assume","assumes","asthma","at","ate","athletic","atilt","atoll",
    "atom","atone","atony","atop","atopy","att","attached","attain","attained","attains",
    "attar","attempt","attend","attends","attest","attests","attic","attire","attracts","attune",
    "attunes","auburn","auction","audible","audio","augment","augur","auk","aulic","aunt",
    "aunty","aura","authors","auto","avail","ave","avenges","avens","average","averse",
    "avert","avian","avid","avion","avoid","avowed","aw","awake","awakens","award",
    "aware","awash","away","awe","awed","awful","awl","awn","awoke","ax",
    "axe","axial","axile","axiom","ay","aye","azine","azines","azole","azoth",
    "azuki","azure","azyme","ba","baa","baaed","babble","babbled","baby","back",
    "backbone","backed","backfire","bacon","bad","bade","badge","badger","badly","bag",
    "bagel","baggy","bagpipe","bail","bait","baking","balance","balanced","bale","bales",
    "ball","ballot","balm","balmy","bamboo","ban","band","bandit","bandy","bane",
    "bang","banish","banjo","bank","bankrupt","banter","bar","barbe","barbed","bardo",
    "bare","bared","barely","bargain","barge","bark","barn","baron","barrel","baseline",
    "bash","basic","basin","basis","bask","basket","bass","baste","bat","batch",
    "bath","bathe","baton","bats","batten","battle","bawdy","bawl","bay","bayou",
    "be","beach","beacon","bead","beady","beam","bean","bear","beard","beast",
    "beat","beaten","bebop","because","becoming","bed","bedlam","been","beer","beet",
    "befall","befit","befoul","beg","began","begin","beginner","behave","behaved","behind",
    "beige","being","belief","beliefs","believe","believed","bell","belle","belong","belongs",
    "below","belt","bench","bend","bended","benefit","bent","benzene","benzine","benzinyl",
    "benzo","benzoyl","benzyl","beryl","beside","besides","best","bestow","bet","betaine",
    "betel","betray","bevel","bevy","bewit","beyond","bezil","bi","bias","bible",
    "bicker","bid","bidden","bide","bidet","big","bight","bigot","bijou","bike",
    "bile","bill","billion","bin","bind","biome","birch","bird","birth","birthday",
    "bisect","bit","bite","bits","bivvy","black","blackout","blade","blame","blamed",
    "blanch","bland","blank","blare","blase","blast","blaze","blazon","bleak","bleat",
    "bleed","blend","bless","blight","blights","blind","blink","bliss","blob","blocking",
    "blog","bloke","blond","blood","bloom","blossom","blouse","blow","blown","blue",
    "blues","blunt","blur","blurt","bo","boar","board","boast","boat","bode",
    "bodily","body","bog","boggle","boggy","bold","boldly","bolen","bolt","bomb",
    "bond","bonding","bone","boney","bonnet","bonny","bonus","boo","booby","book",
    "boom","boon","boot","booze","bop","borax","border","borders","bore","bored",
    "born","borrowed","boss","bot","botch","both","bother","bottle","bottles","bough",
    "bounce","bounced","bouncy","bound","bounty","bout","bow","bowl","box","boxing",
    "boy","bra","branch","brave","bravely","brawl","brawn","braxy","braze","breach",
    "bread","breadth","break","breast","breath","breathe","breed","breezy","bribe","bribed",
    "bridal","bride","bridge","bridges","bridle","brief","briefly","bright","brimmed","brine",
    "brink","briny","brisk","broad","broadly","broil","broke","broken","brooch","brood",
    "brook","broth","brows","brunt","brush","brutal","brute","bubble","buckle","bud",
    "buddy","budge","buffer","bug","buggy","bugle","building","built","bulge","bulk",
    "bulky","bull","bully","bump","bun","bunch","bunched","bunk","bunny","buoy",
    "bur","burden","burke","burly","burn","burnt","burp","burrow","bursa","bursting",
    "bury","bus","bush","bushy","business","busted","but","butane","butch","butene",
    "butyl","butyne","buxom","buy","buzz","bwleo","by","bygone","bylaw","bypass",
    "byway","byword","cab","cabal","cabin","cabinet","cable","cactus","cadet","cadge",
    "cafe","cage","cairn","cake","calendar","calf","calix","call","callus","calm",
    "calming","calmly","calyx","cam","came","camel","cameo","camp","campaign","can",
    "candid","candle","candor","candy","cane","canid","canny","canoe","canon","canopy",
    "cap","capable","capacity","cape","caper","captain","capture","captured","car","carbon",
    "card","carding","care","cared","careful","careless","cares","caret","cargo","carmine",
    "carminy","carob","carol","carom","carp","carpet","carried","carry","carrying","cart",
    "carte","carton","carve","carvings","case","cases","cash","cast","caste","castle",
    "casual","cat","catch","category","cater","catty","caught","caulk","cause","causing",
    "cave","cavern","cavil","cavity","caw","cedar","cede","ceiling","ceilings","cell",
    "cement","census","central","century","cereal","ceremony","cerise","certain","cesta","chad",
    "chafe","chalk","chalky","champ","chance","chances","changed","chaos","chapel","chapter",
    "charade","charge","charged","charity","charm","chart","chary","chase","chasing","chasm",
    "cheap","cheaply","cheat","checks","cheek","cheer","cheered","cheery","cheese","chef",
    "chemical","cherry","chess","chest","chewy","chicken","chide","chief","child","children",
    "chilled","chilly","chimp","chin","china","chip","chipped","chirp","chivy","choice",
    "choices","choking","choline","cholinyl","chop","chord","chore","chose","chrome","chump",
    "chunk","cilia","circle","circles","circuit","cite","citizens","citrus","city","civic",
    "civil","civvy","clack","claim","clam","clamor","clamour","clamp","clan","clang",
    "clank","clap","claps","clash","clasp","class","classes","classy","claw","clay",
    "clean","clear","clearly","cleave","cleft","clench","clever","click","clicked","cliff",
    "cliffed","climate","climb","climbers","climbing","cling","clingers","clink","cloak","clock",
    "clone","close","closely","closet","closing","cloth","clothes","cloud","cloudly","cluck",
    "clue","clumped","clumsy","clunk","coapt","coarse","coat","coating","cob","cobalt",
    "cobble","cobby","cobra","cocoa","cod","codify","codon","coil","coined","col",
    "cola","cold","coldest","collapse","collect","collide","colon","colony","combat","combine",
    "combined","come","comedy","comet","comfort","comfy","comic","coming","comma","command",
    "comment","commits","common","compels","compete","compiled","complete","complex","comply","computed",
    "con","conceal","cone","confer","confers","confined","confirm","conflict","confuse","congress",
    "conic","connect","consent","consider","constant","contact","contains","content","continue","control",
    "controls","convert","convict","convince","cook","cool","cop","copal","cope","copper",
    "copying","cor","coral","cord","core","cork","corn","corner","corny","corset",
    "cos","cost","costly","cot","cotton","couch","could","council","counsel","count",
    "counted","country","county","coup","couple","coupled","coups","courage","court","cover",
    "covert","covet","cow","coward","cowards","cower","cox","coy","coyly","cozie",
    "crack","crafted","crafty","crake","cramp","crane","crank","cranky","cranny","crash",
    "crate","crave","crawl","crayon","crayons","creak","creaky","cream","create","creates",
    "creative","credit","credits","creed","creek","creel","creep","crest","crew","crimp",
    "crisp","crispy","croak","crone","croon","crop","cross","crossed","croup","crow",
    "crowd","crowded","crown","cruel","cruft","crumb","cruse","crush","crushed","crust",
    "crusty","crutch","crypt","cub","cube","cubic","cud","cuddle","cultural","culture",
    "cunning","cup","cur","curb","cure","curer","curios","curl","curly","cursed",
    "curtain","cushion","cushy","custard","customer","customs","cut","cute","cutey","cyan",
    "cycle","cysteine","cytosine","da","dab","dad","daddy","daffy","daft","dag",
    "dagger","daily","dais","daisy","dale","dales","dally","dam","damage","damaged",
    "dame","damp","dampen","dampy","damsel","dance","dancer","dancing","dandy","danger",
    "dapper","darby","dare","daren","dark","darken","darn","dart","dash","dashing",
    "data","date","dated","dater","datil","daube","daughter","daunt","daw","dawdled",
    "dawn","day","daze","dazzle","dazzled","de","dead","deadline","deadly","deaf",
    "deal","dealing","deals","dealt","dean","dear","dearly","deb","debar","debug",
    "debut","decade","decal","decent","decided","declare","declared","decline","decode","decoder",
    "decoy","decry","deed","deepen","deer","defeated","defend","defended","defense","defiant",
    "define","defined","definite","deftly","deify","deity","delayed","delete","deliver","dell",
    "delude","deluge","deluxe","demand","demands","demise","demo","demy","denial","deny",
    "deploy","deployed","depot","depth","derby","describe","desert","deserve","design","designed",
    "desired","desk","desktop","destined","detached","detailed","detour","deuce","devises","devote",
    "devoted","devotes","dhole","dhow","dial","diamond","dice","died","diet","differ",
    "differs","dig","digger","digit","dill","dilly","dim","dime","dimmers","dimple",
    "dine","dip","dire","direct","directed","directs","dirk","dirt","dirty","dis",
    "disable","disabled","disarm","disarms","disaster","disc","disclose","disco","discover","discuss",
    "dish","disk","dismal","dismiss","display","diss","distant","distinct","dit","ditch",
    "ditty","ditzy","diva","divert","divide","divided","divine","divorce","dizen","dizzy",
    "do","docile","dock","dodge","dodger","dog","dogma","dojo","dolce","dollar",
    "dolma","domain","dome","domed","dominant","don","done","donkey","donor","door",
    "dopey","dose","dot","dote","doting","dotted","dotting","dotty","double","doubled",
    "doubt","dough","dove","dow","dowdy","dowel","down","downtown","dowry","drab",
    "draft","drag","dragged","dragon","dragons","drain","drake","drama","dramatic","drapes",
    "draping","drastic","draw","drawback","drawing","drawl","dread","dream","dreamy","dregs",
    "dress","dresses","dressing","drew","dried","drift","drifting","drill","drink","drip",
    "drive","driven","driving","droit","drone","drool","droop","drop","droplet","drought",
    "drove","drown","drowse","drowsy","drudge","drugs","drum","drummed","dry","dryer",
    "dual","dub","dud","due","duel","dues","dug","dulcet","dull","duly",
    "dumb","dummies","dump","dumpling","dun","dunk","duo","dupe","durable","duress",
    "during","dusk","dusky","dust","duty","dwarf","dweeb","dwell","dye","each",
    "eager","eagerly","eagle","ear","earl","early","earn","earns","earth","earthy",
    "ease","easel","easily","east","easy","eat","eating","eats","eclat","economic",
    "ed","edge","edged","edging","edit","editors","educated","eel","eerie","ef",
    "effort","egads","egg","ego","egret","eh","eight","either","eking","el",
    "elapsed","elate","elated","elbow","elder","elegy","elevate","elevated","eleven","elf",
    "elfin","elicit","elite","elixir","elk","elm","else","elude","em","embar",
    "embassy","embow","embrace","embus","emcee","emerged","emirt","emit","emmet","emote",
    "emotion","emotions","emphasis","empire","employ","employed","employee","empower","emu","en",
    "enable","enabled","enact","encase","encased","enclosed","encode","encoding","encore","end",
    "endue","endure","enema","enforce","engage","engaged","engulf","enhance","enjoin","enjoyed",
    "enlarged","enlist","enorm","enormous","enough","enriched","ensign","ensue","ensure","ensures",
    "entered","entire","entirely","entrance","entries","envied","envious","envoy","envy","enzyme",
    "epic","episode","epoxy","equip","equipped","er","era","erect","ergot","errands",
    "errant","eruct","erupt","erupted","es","escape","escaped","esprit","essay","essence",
    "estate","estimate","estuary","et","ethane","ethanol","ethene","ethic","ethyl","ethyne",
    "etude","evade","evaluate","eve","even","evening","evenly","ever","every","evidence",
    "evident","evil","evoke","evolve","ewe","ex","exact","exactly","exalt","exam",
    "examine","examined","example","exceeded","excel","excite","excited","excites","exempt","exercise",
    "exert","exhaled","exhaust","exile","exist","existed","existing","exit","expand","expanded",
    "expat","expected","expire","explains","explore","explored","expose","exposed","extend","extended",
    "extends","external","extra","extreme","exude","exult","eye","eyed","eyrie","eyrir",
    "fa","fab","fabled","face","facial","fact","factors","factory","fad","fade",
    "faded","fail","failure","faint","fainted","fair","fairy","faith","fake","fakir",
    "fall","fallback","fallen","false","falters","fame","familiar","famine","fan","fancy",
    "fanfare","fantasy","far","farce","fare","farm","farming","fashion","fast","fat",
    "fatal","fate","fathom","favus","fawn","fax","fay","faze","fe","feast",
    "feasted","featured","fecal","fed","feign","feline","felon","fen","fenny","feral",
    "fern","ferret","ferry","fertile","fest","fester","fetal","fetch","fetched","fete",
    "fetid","fetish","fetter","feud","fever","few","fewer","fez","fib","fibula",
    "fickle","fiction","fiddly","fiery","fifth","fifty","fig","fight","fighting","fights",
    "figure","file","filet","fill","film","filter","filtered","fin","finally","finance",
    "finch","find","fine","finger","fingers","finial","finished","fir","fire","firm",
    "fiscal","fish","fishes","fissure","fist","fit","fitful","fix","fixture","fiz",
    "fizzing","fizzy","flab","flack","flag","flair","flakes","flame","flames","flaming",
    "flank","flanked","flap","flare","flash","flashed","flashing","flask","flat","flaw",
    "flawed","flay","fleck","fled","fledge","flee","flesh","flex","flick","flicker",
    "flight","flights","flinch","fling","flint","flinty","flip","flirt","float","floated",
    "flock","flood","flooded","floor","floors","flop","flora","florid","flour","flout",
    "flow","flowers","fluent","fluff","fluke","fluky","flunk","flurry","flute","flutter",
    "fly","flying","foal","foam","foamy","fob","focal","focused","foe","fog",
    "fogey","foggy","foil","folio","folk","folksy","followed","folly","fon","fond",
    "fondly","font","fool","footer","fop","for","force","ford","fore","foreign",
    "forest","forex","forge","forged","fork","form","formal","formally","formerly","forming",
    "formula","fort","forth","forward","foster","fought","foul","found","founded","founder",
    "four","fowl","fox","foyer","fraction","fragment","frail","framing","franc","frank",
    "fraud","fray","freak","free","freedom","frequent","fresh","freshly","fried","friendly",
    "frisk","fritz","frog","from","front","fronted","frosted","frowning","frowns","froze",
    "frozen","frugal","fruit","fry","fub","fuddle","fudge","fuel","fug","fugue",
    "full","fully","fume","fun","fungi","funk","funky","funnily","funny","fur",
    "furan","furanyl","fury","fuse","fussy","future","futurity","fuzzy","gab","gabby",
    "gad","gadge","gag","gagged","gaining","gal","gale","gall","gambe","gamble",
    "gambled","game","gamut","gander","gang","gangy","gap","garble","garden","gardens",
    "garish","garment","garner","gas","gash","gate","gathered","gaudy","gauge","gauze",
    "gauzy","gave","gawk","gawky","gay","gaze","gecko","gel","geld","gem",
    "general","generate","generous","genial","gentle","gesture","get","ghyll","gi","giddy",
    "gift","gig","giggle","giggly","gild","gilded","gin","gird","girded","girl",
    "girth","give","given","glad","gland","glare","gleamed","glean","glee","glen",
    "glib","glide","glint","glinted","glob","glogg","gloom","gloomy","gloss","glottal",
    "glove","glow","glower","glowing","glum","glume","glycan","glycin","glycine","glycinyl",
    "glycol","glyph","gnarly","gnash","gnome","gnu","go","goalie","goat","gobble",
    "goblet","god","godly","gold","golden","golem","golf","good","goody","goon",
    "goose","gore","gory","got","gouge","gourd","gouty","govern","gown","grab",
    "grabbed","grace","graceful","grade","grading","grain","gram","granted","grapes","graphic",
    "grasp","grasped","grassy","grate","grateful","gravel","gravely","gravity","gravy","gray",
    "graze","great","greater","greatly","grebe","greed","green","greet","grew","grid",
    "grief","grieve","grille","grim","grin","grip","gripe","grippe","gripped","grisly",
    "grit","groan","groaned","grocer","groin","groom","grope","gross","grounds","grouped",
    "grouse","grout","grove","grovel","grow","growing","growl","grub","grudge","gruel",
    "gruff","grump","grumpy","guanine","guard","guarded","guava","guess","guest","guide",
    "guiding","guile","guilty","guise","gulf","gull","gulp","gum","gun","gunky",
    "gush","gust","gusto","gusty","gut","guts","gutter","guttural","guy","guyot",
    "gym","gyrate","ha","habit","habitat","hack","had","hadj","hag","haggle",
    "haggled","hail","hair","half","hall","halt","halve","ham","hammers","hammy",
    "hamper","hamza","hand","handful","handle","handled","handling","handy","hang","hanging",
    "hank","hap","hapless","haply","happen","happened","happy","harbour","hard","hardly",
    "hare","hark","harken","harm","harmony","harp","hart","has","hash","hassle",
    "hasten","hasty","hat","hate","hater","haughty","haul","haunt","have","haven",
    "haw","hay","haze","hazel","he","head","heady","heal","healthy","heap",
    "hear","hearing","heart","heel","heft","hefty","helm","help","helping","hem",
    "hen","hence","hep","her","herald","herb","herbal","herbs","herby","herd",
    "heritage","hero","heroic","heron","hew","hewn","hex","hey","hi","hid",
    "hidden","hide","high","hiking","hill","hilt","him","hind","hinder","hinge",
    "hint","hip","hippo","hippy","hire","his","hissing","history","hit","hive",
    "hm","ho","hoard","hoax","hob","hobby","hockey","hod","hoe","hog",
    "hoisted","hokey","holey","holler","hollow","holly","homage","homeland","homely","homer",
    "homey","honest","honey","honor","honours","hoop","hoops","hop","hope","hopping",
    "hoppy","horde","horizon","horn","horse","horsy","hospital","hostile","hot","hotly",
    "hour","housing","hovel","hover","how","howdy","howl","hub","hue","huffy",
    "hug","hugely","hull","hum","human","humanity","humble","humid","humor","hump",
    "humpy","hun","hung","hunger","hungry","hunk","hunky","hunt","hunter","hurl",
    "hurtle","husband","hussy","hustle","hut","hyena","hymn","hyoid","ice","icing",
    "icon","iconic","icy","id","ideal","ideate","idiom","idiot","idle","if",
    "igloo","ignite","ignored","ilk","ill","illegal","illness","ills","image","imagery",
    "imagine","imam","imbue","immune","imp","impel","impend","imply","import","imposed",
    "impound","improve","improved","impure","in","inane","inch","incline","include","includes",
    "increase","incur","indie","indole","indolyl","inept","inert","infected","infer","infix",
    "info","informed","infused","inherit","injured","ink","inkle","inlay","inlet","inlets",
    "inn","inner","innocent","insane","inset","insets","insights","insist","inspired","instead",
    "integral","intend","intends","inter","intro","invent","invite","invited","invoke","involve",
    "involved","ion","ionic","irate","ire","iris","iron","is","island","islands",
    "isle","isolate","isolated","isomer","isomers","it","itch","itself","ivory","ivy",
    "jab","jack","jade","jag","jagged","jail","jam","jamb","jangle","jar",
    "jaunt","jaw","jay","jazzy","jeep","jeer","jell","jelly","jest","jewel",
    "jib","jibe","jibed","jiffy","jig","jiggle","jilt","jingo","jo","job",
    "jog","join","jointly","joke","joker","jokey","jolt","jolty","jostle","jot",
    "journal","joust","jovial","jowl","joy","jug","juice","juicy","julep","jump",
    "jumping","jumpy","jungle","junior","junk","just","jut","ka","karst","kazoo",
    "kebab","keel","keen","keep","keeping","keg","ketol","ketone","key","keyboard",
    "ki","kicking","kid","kill","kiln","kin","kind","kindle","kindly","king",
    "kingdom","kinky","kit","kitchen","kite","knap","knave","kneel","knelt","knew",
    "knife","knit","knob","knocked","knoll","knot","knotty","know","knower","knowing",
    "known","kudos","la","lab","labor","lac","lace","laces","lack","lades",
    "lads","lag","lahar","laid","lake","lamb","lame","lament","lamp","lance",
    "lancer","land","landing","lane","lanes","lange","lank","lanky","lap","lapel",
    "larch","lard","largely","largo","lark","laser","lash","last","lasting","latch",
    "late","later","lathe","lather","latte","laud","laugh","laughed","laughing","launch",
    "launched","lava","lavish","law","lawn","lax","lay","layer","lazar","laze",
    "lazy","lea","lead","leading","leads","leaf","leafy","leak","leaky","lean",
    "leapt","learn","learned","lease","least","led","leg","legan","leggy","leisure",
    "lemon","lena","lend","lending","lens","lessen","lest","let","letter","letters",
    "leucine","leucinyl","level","lever","leverage","levy","li","libel","liberty","lid",
    "lied","liege","lieu","life","lifetime","lift","light","lights","likely","lilac",
    "lilt","lima","limb","lime","limes","limit","limited","limp","line","liner",
    "linger","lingo","link","linking","lion","lip","lipase","lipid","lipoid","lipoma",
    "lispy","list","listen","listing","lit","literary","litmus","live","lively","liver",
    "lizard","llama","lo","load","loan","loans","located","location","loch","lock",
    "lodge","lodger","loft","lofty","log","logging","logic","logical","loin","lone",
    "long","longest","look","looking","loom","loon","loopy","loose","loosely","loosen",
    "lore","loss","lot","loud","lounge","lout","love","lover","loving","low",
    "lucid","luck","lucky","lucre","lug","lull","lumber","lumen","lump","lumpy",
    "lunar","lunch","lung","lunging","lure","lurk","lust","luster","lusty","lute",
    "lyric","lysine","lysinyl","ma","mace","macro","mad","madcap","made","madly",
    "madman","mafia","magic","magnetic","maid","mail","maim","major","maker","male",
    "mall","malt","man","managed","managing","mane","maner","manes","manga","mangle",
    "mango","manly","manner","manor","map","maple","mar","marble","marce","march",
    "mare","mark","marry","mars","marvel","mason","mast","mat","match","matching",
    "mate","material","mates","math","maven","maw","maxim","maximum","may","mayhem",
    "mayor","maze","me","mead","meal","mealy","mean","meaning","means","measly",
    "measure","measured","meat","meats","meddle","media","medical","meek","meeting","melee",
    "mellow","melody","melon","memo","memory","men","mend","mercy","mere","merge",
    "merger","merit","mesh","mesne","messy","met","methane","methyl","mew","mezel",
    "mi","mid","midway","miff","might","mights","mighty","mile","miles","military",
    "mimic","mince","mingle","minimize","minimum","minion","mirror","mirth","missile","missing",
    "mist","mistake","misuse","miter","mitre","mitt","mix","mixed","mixture","mm",
    "mo","moans","moat","mob","mock","mocked","mod","modal","mode","model",
    "mogul","mole","molt","molten","mom","monitor","monkish","monks","monster","moody",
    "moon","moor","moose","moot","mop","moral","morale","more","morning","morph",
    "morsel","mortal","mosaic","moss","moth","motif","mountain","mounted","mousy","mouth",
    "mouthy","movement","mow","mu","muck","mud","muddle","muddy","muffin","mug",
    "muggy","mulch","mulct","multiple","mum","mural","murky","muscle","muscles","music",
    "musk","must","muster","musty","mutt","mutton","my","myrrh","mystery","mystic",
    "mystify","myth","na","nab","nag","naiad","nail","nails","name","namer",
    "names","nanny","nap","narrow","nasal","nasty","national","natty","natural","nature",
    "naval","navy","ne","near","nearby","nears","neat","neatly","neck","need",
    "needle","needy","negative","neon","nephew","neros","nerve","nervy","nest","nestle",
    "network","news","next","nice","nick","nifty","nigh","night","nights","nimble",
    "ninja","ninny","nippy","nix","no","nob","noble","nod","node","noel",
    "noir","noise","noisy","nonce","noodle","nook","nope","nor","norm","normal",
    "north","nose","noser","not","notably","notch","note","notebook","notes","nought",
    "nourish","novel","novice","now","nu","nubby","nuclear","nude","nudge","null",
    "numb","nun","nurse","nurtured","nut","nymph","oaf","oafish","oafy","oak",
    "oaken","oakum","oar","oat","oath","obeah","obese","obey","object","oblong",
    "obtain","obtuse","obvious","occur","ocean","octet","od","odd","oddly","ode",
    "odious","oe","of","off","offal","offend","offered","offhand","official","offset",
    "oft","ogre","oh","ohm","oi","oil","ok","okapi","okay","old",
    "olive","om","omega","omen","omer","omit","on","once","one","onlooker",
    "only","onset","onto","onward","oozing","op","open","opening","opera","opinion",
    "opt","opts","or","oral","orate","orb","orbit","orbs","orchid","ordeal",
    "ordered","ore","organ","organic","organize","ortho","os","other","otiose","otter",
    "otto","our","out","outbid","outdo","outdoor","outer","outlaw","outline","output",
    "outrun","outside","outwit","ovary","oven","over","ovoid","ow","owe","owed",
    "owl","own","owned","owns","ox","oxazine","oxazines","oxazole","oxazolyl","oxbird",
    "oxbow","oxcart","oxford","oxgang","oxgate","oxhide","oxide","oxime","oxlip","oxtail",
    "oxter","oy","oyster","ozone","pa","paced","pack","packing","pad","padre",
    "pagan","page","pail","pails","paint","painted","pair","pairing","pairs","pal",
    "palace","palate","pale","pall","palm","palmy","pam","pan","pander","pane",
    "panel","pang","panic","pansy","pant","pantry","pants","panty","pap","papal",
    "papaya","paper","papery","par","pardon","paris","parish","parky","parlor","parody",
    "parrot","parry","parse","part","parting","partner","parts","partway","party","passing",
    "passion","pasta","paste","pat","patchy","pathway","patrol","patron","patrons","patsy",
    "patter","pattern","pauper","pause","pave","paw","pawky","pawn","pay","payee",
    "pe","pea","peace","peach","peak","pear","pearl","pears","peat","peddle",
    "peel","peer","peg","pelf","pen","penal","penis","penny","pep","pepper",
    "pepsin","pepsinyl","per","perch","perhaps","peril","perk","perky","permit","pesky",
    "pest","pester","pet","petal","petite","petty","pew","pewter","phage","phase",
    "phenol","phenyl","phial","phlox","photo","physical","pi","piano","picket","pickle",
    "picture","pig","piglet","pike","pile","piles","pilfer","pill","pilot","pin",
    "pinch","pine","pines","pink","pinned","pint","pioneer","pipe","pirate","pistol",
    "pit","pithy","pitiless","pixel","pixie","pizza","place","places","placid","placing",
    "plaid","plain","plan","plane","plank","planned","plant","plastic","plate","player",
    "plaza","plead","pleat","plenty","pliant","plied","plies","plight","plodded","plodding",
    "plonk","plop","plot","plow","ploy","pluck","plum","plumb","plumber","plume",
    "plunge","plunged","plunk","plus","plush","ply","po","pod","podgy","poem",
    "poet","poetry","poggy","poi","point","pointed","poise","poker","polar","polling",
    "polo","polyp","pond","ponder","pony","pool","poor","pop","popsy","popular",
    "pore","pores","port","portal","porting","pose","posh","positive","post","postal",
    "pot","potent","pots","potty","pouch","pouchy","pound","pour","pout","pow",
    "power","practice","practise","praise","prawn","pray","preach","precious","prefer","preserve",
    "press","pretty","previous","prey","price","pride","prideful","priest","prime","primer",
    "primp","priority","prism","prison","prissy","privy","pro","probable","probe","process",
    "prod","produce","progress","proline","prolinyl","prone","prong","proof","prop","propane",
    "propel","proper","property","proposal","propyl","prose","protect","proven","provide","prowl",
    "prude","prune","pry","prying","psalm","pub","public","publish","puddle","pudgy",
    "puffy","pug","pull","pulse","pummel","pump","pun","pungent","punish","punky",
    "pup","purge","purine","purinyl","purpose","purse","pus","put","puzzle","pygmy",
    "pyran","pyre","pyridine","pyrone","pyrrol","pyrrole","qi","quaff","qualify","quality",
    "qualm","quarry","quarter","quasi","quench","query","quest","queue","quiet","quietly",
    "quince","quinic","quinoa","quinol","quinoyl","quippy","quirk","quirky","quit","quitch",
    "quota","quote","quoth","rabbi","rabbit","rabble","race","raced","racer","races",
    "rack","radar","radical","radon","rag","ragged","raid","rails","rain","rainy",
    "raise","rajah","rake","rally","ram","ramen","ramp","ranch","random","rang",
    "range","rank","rankle","rant","rap","rape","rapid","rapidly","rapt","rare",
    "rarely","rash","rasp","rat","rate","rated","ratel","rates","rathe","rather",
    "rattle","ratty","ravage","rave","raven","raw","ray","rayon","raze","razed",
    "razor","re","reach","reached","reaching","react","read","readily","reading","real",
    "realign","reality","ream","reap","reaps","rearm","reason","rebel","rebuilt","rebuke",
    "rebus","recede","recent","reckon","recoil","record","records","red","redden","reduce",
    "reduced","reedy","reeky","reel","ref","refill","reform","refugee","refuse","regal",
    "regime","regions","regular","reign","rein","reins","reject","rejoice","related","relax",
    "release","rely","relying","remains","remark","remedy","remit","renal","rend","render",
    "rent","rep","repair","repairs","repay","repeal","repeat","replace","reply","reports",
    "rerun","resent","reserve","resign","resin","resolve","resource","respect","respond","response",
    "rest","restore","result","retail","retas","return","rev","reveal","revenue","reverse",
    "revised","revive","revived","rib","rice","rick","rid","ride","riff","riffy",
    "rifled","rift","rig","right","rights","rim","rime","rind","ring","rink",
    "rinse","riot","rip","ripple","rise","risen","risk","risky","ritzy","rival",
    "river","rivet","road","roam","roaming","roan","roar","roast","rob","robe",
    "robin","robust","rock","rocky","rod","rode","rodeo","role","roll","rome",
    "romp","roof","room","roomy","roost","root","rope","ropes","roping","rose",
    "rosy","rot","rotate","rouge","rough","rouse","rout","routine","rove","row",
    "rowdy","royal","rub","ruddy","rude","rueful","rug","rugby","rugged","ruin",
    "rule","ruler","rum","rummy","run","running","runny","runt","rupee","rural",
    "ruse","rush","rust","rustle","rusty","rut","ruthless","ruts","rye","sabot",
    "sac","sad","saddle","sadly","safe","safely","sag","saga","sage","sail",
    "sailor","saint","sake","sale","salt","salve","salvo","same","sample","sand",
    "sandal","sandy","sane","sang","sanity","sank","sap","sash","sassy","sat",
    "savage","save","savings","savor","savvy","saw","sax","say","scald","scales",
    "scaling","scalp","scaly","scan","scant","scar","scare","scarf","scarp","scarred",
    "scene","scenery","schedule","school","schools","science","scoff","scold","scone","scoop",
    "scope","scorch","score","scorn","scout","scram","scrap","scrawl","scream","scree",
    "screw","scroll","scrub","scud","scurry","sea","seam","seats","seconds","section",
    "secure","security","seedy","seeking","seem","seen","seep","seepy","seethe","seize",
    "seldom","self","sell","send","senor","senot","sense","sensing","sensor","sent",
    "sentence","separate","sepoy","serf","serinal","serine","serious","serve","service","serving",
    "set","setting","settings","settle","settled","seven","sever","several","severe","sew",
    "sex","sh","shack","shadows","shady","shaft","shag","shake","shaky","shall",
    "shallow","sham","shame","shape","shard","share","sharing","shark","sharp","shave",
    "shawl","shear","shed","sheep","shelf","shell","shelter","shield","shift","shifting",
    "shimmer","shin","shine","shining","shirt","shoal","shocked","shoer","shone","shook",
    "shop","shore","short","shot","shout","shouted","shove","show","shown","shred",
    "shrew","shrewd","shrub","shrug","shuck","shunt","shut","shy","si","sick",
    "side","siege","sieve","sift","sigh","sighing","sight","sighted","sights","sigma",
    "signal","signing","silence","silent","silk","sill","silo","silt","similar","simple",
    "sin","sing","singer","single","singlet","sink","sip","sipped","sir","siren",
    "sis","sit","sitting","sixth","sixty","skate","sketch","skew","ski","skid",
    "skim","skimp","skin","skip","skirt","skull","sky","slab","slack","slag",
    "slain","slang","slant","slap","slat","slate","slave","sled","sleek","sleep",
    "sleet","slender","slept","slew","slick","slide","sliding","slight","slim","slime",
    "slimy","slip","slipe","slipped","slippy","slit","sliver","slob","slop","slope",
    "slosh","slot","sloth","slow","sludge","slug","slum","slummy","slur","sly",
    "smack","small","smash","smear","smile","smirk","smite","smoke","smoky","smug",
    "snag","snail","snake","sname","snap","snare","snatch","sniff","snip","snipe",
    "snob","snog","snooty","snore","snort","snote","snowy","snub","so","soak",
    "soar","soaring","sob","sock","sod","sofa","soggy","soil","solar","soldier",
    "sole","solely","solemn","solution","solve","solving","some","somehow","someone","son",
    "song","soot","soothe","sooty","sop","soppy","sordid","sore","sort","sorting",
    "soul","sounded","soup","soupy","sour","south","sow","soy","spa","span",
    "spar","spare","spark","sparky","spawn","speaking","spear","species","speck","spend",
    "spending","spew","spice","spiky","spile","spill","spin","spine","spiral","spit",
    "spite","splay","sponsor","spook","spooky","spool","spore","spot","spotted","spout",
    "sprawl","spray","spree","sprig","sprout","spud","spumy","spunk","spur","spy",
    "squad","squall","squat","squeak","squid","sri","stab","stable","stack","stag",
    "stagey","stagger","staid","stain","stair","stake","stale","stall","stamp","stand",
    "standard","stank","staple","star","stare","stark","started","starve","stash","state",
    "static","stave","stay","staying","stead","steak","steal","steam","steel","steely",
    "steep","steer","stein","steins","stem","step","stern","sternly","steroid","sterol",
    "sterols","stew","stiff","stifle","still","sting","stink","stir","stock","stodgy",
    "stogy","stoic","stomach","stomp","stone","stony","stood","stool","stoop","stop",
    "store","storing","storm","stormy","story","stout","stove","strange","strap","strategy",
    "straw","stray","strength","stretch","string","strings","strip","stripe","stripes","strive",
    "strived","stroll","struggle","strum","strung","strut","stub","stuck","stud","student",
    "studied","studio","study","stuffy","stump","stumped","stumpy","stun","stung","stunk",
    "stunt","stupid","stupor","sty","suave","sub","subject","subtle","subtly","such",
    "sucker","sucky","suds","sudsy","sue","suffer","sugar","suit","suite","sulk",
    "sulky","summer","summon","sump","sun","sung","sunk","sunny","sunrise","sup",
    "super","supple","support","supra","sure","surface","surge","surges","surly","survive",
    "swab","swag","swam","swamp","swan","swap","swapped","sware","swat","swear",
    "sweat","sweep","sweet","swept","swill","swim","swipe","swirl","switch","swoop",
    "sword","swum","symbol","sync","syrup","system","ta","tab","tabby","table",
    "tack","tackle","tacky","tactics","taffy","tailor","taint","tale","taler","tales",
    "talk","talking","talky","tall","tally","talon","tame","tamely","tames","tan",
    "tangle","tango","tangy","tap","tapir","taps","tar","tare","tares","targets",
    "tarp","tartan","task","tat","taunt","taut","tawny","tax","taxi","tea",
    "teach","teacher","teak","teal","teals","teams","tear","tears","teas","tease",
    "teem","teeny","teeter","teeth","tell","telling","temper","ten","tend","tender",
    "tenor","tense","tent","tepid","term","terpene","terpenyl","terrible","terse","test",
    "testing","testy","tether","text","than","thare","that","thatch","the","thee",
    "theft","their","them","theme","then","there","these","they","thiazine","thiazole",
    "thiazoyl","thick","thing","things","think","thorn","thorny","those","thought","three",
    "threw","throw","thrum","thud","thump","thymine","thymol","thymyl","ti","tick",
    "ticking","tickle","tidal","tide","tie","tiff","tiger","tight","tights","til",
    "tilde","tile","tilt","tilting","timbre","time","timely","timer","tin","tines",
    "tinge","tingle","tinsel","tint","tinted","tip","tipping","tipple","tipsy","tiptoe",
    "tire","tired","title","titled","to","toad","today","toe","toffy","together",
    "toggle","togs","toil","token","toll","toluene","toluol","tom","tome","tone",
    "tones","tong","tongue","tonic","too","top","topple","tops","torc","tore",
    "torn","torso","tort","toss","tossed","total","totally","touch","touched","touchy",
    "tough","tour","tow","towards","towel","tower","toxic","toy","trace","tracked",
    "trade","trading","trail","train","trained","trait","traitor","tramp","trance","transfer",
    "transit","trap","traps","trash","travel","travels","trawl","tread","treat","trend",
    "triad","trial","tribal","trick","tried","tripe","tripes","triple","trips","trite",
    "trod","troll","tromp","trope","trouble","trout","trove","troy","truce","truck",
    "trudge","true","trump","trunk","try","tryst","tub","tubby","tube","tuft",
    "tug","tulip","tumble","tumid","tummy","tun","tune","tuner","tunic","turf",
    "turgid","turning","turnip","tushy","tussle","twerp","twice","twig","twill","twin",
    "twine","twinge","twirl","twist","twisty","two","tycoon","tying","tyke","tykey",
    "typical","tyre","tyrosine","udder","ugly","uh","ulcer","ultimate","ultra","um",
    "un","unclear","uncover","uncut","undo","unease","unfed","unfit","unfold","unicorn",
    "uniform","unify","union","unit","unity","universe","unkind","unknown","unless","unlit",
    "unrest","untidy","until","unused","unusual","unwind","unzip","up","update","upend",
    "upgrade","uphold","uplift","upon","upper","uproot","upset","uptown","uracil","uracilyl",
    "urban","urging","urn","us","usable","usage","use","used","useful","usher",
    "ut","utmost","utter","vacant","vague","vain","vale","valid","valine","valinyl",
    "valley","valleys","valor","valuable","value","valued","valve","vamp","van","vane",
    "vanish","vapid","vary","varying","vat","vault","vaunt","veil","vein","velvet",
    "verbal","version","very","vest","vet","via","viable","vibe","vicar","vice",
    "victim","video","vie","view","viewing","vigil","vigor","vile","vilify","village",
    "vim","vine","viola","violence","violent","violet","viper","virtue","vise","visible",
    "vision","visited","visual","vivid","vixen","vocal","vodka","void","vole","volt",
    "volume","vote","voter","vow","wad","wade","waft","wag","wager","wagon",
    "waif","wail","waist","wait","waiting","wake","walk","walking","wall","wallow",
    "walrus","waltz","wander","wane","want","war","warble","ward","warden","wardens",
    "warming","warmly","warning","warped","warty","wary","was","wash","washing","wasp",
    "wasting","watch","watched","water","wave","wax","we","weaken","wealth","wears",
    "weary","web","wed","wedge","weedy","weekly","weigh","weird","weld","welfare",
    "welt","went","west","western","whack","whale","whatever","wheat","wheel","where",
    "whether","whiff","while","whilst","whim","whip","whir","whirl","whittle","whose",
    "wick","wicked","wide","widely","widen","widow","wield","wife","wig","wild",
    "wile","will","willing","willow","wilt","wily","wimp","win","windy","wine",
    "wing","wink","winning","winter","wintry","wire","wisdoms","wise","wish","wisp",
    "wit","with","without","witty","wo","wobble","woe","woeful","wok","woke",
    "wolf","woman","womanly","womb","won","woo","wooden","woozy","word","words",
    "wordy","wore","work","working","world","worm","wormy","worn","worried","worsen",
    "worst","worth","wow","wrapped","wrath","wreck","wren","wrest","wrestle","writ",
    "writers","writhe","writing","wrong","wrote","xi","xu","xylene","xyloid","xylose",
    "xyster","ya","yacht","yam","yap","yarn","yaw","ye","yearly","yearn",
    "yell","yew","yield","yin","yip","yo","yodel","yogic","yonder","yore",
    "you","young","your","yourself","youth","yowl","yummy","za","zap","zappy",
    "zeal","zealot","zebra","zed","zero","zest","zesty","zig","zilch","zinc",
    "zincy","zip","zippy","zoeae","zoeal","zoeic","zombi","zonal","zone","zoned",
    "zoo","zooid","zoom","zooms"
  ],

  getPoints(word) {
    return [...word.toLowerCase()].reduce((sum, c) => sum + (this.letterPoints[c] || 0), 0);
  },

  canMakeWord(word, letters) {
    const lowerWord = word.toLowerCase();
    const letterArr = [...letters.toLowerCase()];
    const wildcards = letterArr.filter(c => c === '?' || c === '*').length;
    const available = letterArr.filter(c => c !== '?' && c !== '*');
    let wildcardsUsed = 0;

    for (const ch of lowerWord) {
      const idx = available.indexOf(ch);
      if (idx !== -1) {
        available.splice(idx, 1);
      } else {
        wildcardsUsed++;
        if (wildcardsUsed > wildcards) return false;
      }
    }
    return true;
  },

  unscramble(letters, options = {}) {
    const { startsWith = '', endsWith = '', mustInclude = '', minLen = 2, maxLen = 15, lengthFilter = 'all', sortBy = 'length' } = options;
    const sw = startsWith.toLowerCase();
    const ew = endsWith.toLowerCase();
    const mi = mustInclude.toLowerCase();
    const lf = lengthFilter;

    let results = this.words.filter(word => {
      if (!this.canMakeWord(word, letters)) return false;
      if (sw && !word.startsWith(sw)) return false;
      if (ew && !word.endsWith(ew)) return false;
      if (mi && !word.includes(mi)) return false;
      if (lf !== 'all') {
        if (lf === '8+') { if (word.length < 8) return false; }
        else if (word.length !== parseInt(lf)) return false;
      }
      return true;
    });

    if (sortBy === 'alpha') {
      results.sort();
    } else if (sortBy === 'points') {
      results.sort((a, b) => this.getPoints(b) - this.getPoints(a));
    } else {
      // by length desc
      results.sort((a, b) => b.length - a.length || a.localeCompare(b));
    }

    return results;
  },

  groupByLength(words) {
    const groups = {};
    words.forEach(w => {
      const len = w.length;
      if (!groups[len]) groups[len] = [];
      groups[len].push(w);
    });
    return groups;
  }
};
